version: '2'
services:
    infi-app:
        image: infi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://infi-postgresql:5432/infi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    infi-postgresql:
        extends:
            file: postgresql.yml
            service: infi-postgresql
